app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, redirect, url_for, flash, session, current_app
from flask_login import login_user, logout_user, current_user, login_required
from app.main import bp
from datetime import datetime
from app import db
from app.models import User, BlogPost, AboutMe
from sqlalchemy import exc
from bs4 import BeautifulSoup


@bp.route('/', methods=['GET'])
def index():
    no_posts = False
    blog_posts = None
    preview_list = {}
    try:
        blog_posts = BlogPost.query.filter(BlogPost.hidden!=1).order_by(BlogPost.id.desc()).limit(5).all()
    except exc.SQLAlchemyError:
        current_app.logger.exception("Unable to get blog posts")
    except exc.NoResultFound:
        no_posts = True
        blog_posts = None
    for post in blog_posts:
        soup = BeautifulSoup(post.body, features="html.parser")
        preview_list[post.id] = soup.get_text()[:400]
    return render_template("main/index.html", blog_posts=blog_posts, no_posts=no_posts, preview_list=preview_list)


@bp.route('/about_me', methods=['GET'])
def about_me():
    about_me = None
    try:
        about_me = AboutMe.query.order_by(AboutMe.id.desc()).limit(1).first()
    except exc.SQLAlchemyError:
        current_app.logger.exception("Unable to get latest about me")
    except exc.NoResultFound:
        about_me = None
    return render_template("main/about_me.html", about_me=about_me, title='About Me')


@bp.route('/post/<post_id>', methods=['GET'])
def post(post_id):
    error = None
    blog_post = BlogPost.query.filter(BlogPost.id==post_id, BlogPost.hidden!=1).first()
    try:
        if blog_post is None:
            error = "Unable to find blog post. Please try again or contact the site admin."
        else:
            blog_post.times_loaded += 1
            db.session.add(blog_post)
            db.session.commit()
    except exc.SQLAlchemyError:
        current_app.logger.exception("Unable to update blog post read count")
    except exc.NoResultFound:
        error = "Unable to find blog post. Please try again or contact the site admin."
    return render_template("main/post.html", blog_post=blog_post, error=error)


@bp.route('/all_posts', methods=['GET'])
def all_posts():
    no_posts = False
    blog_posts = None
    preview_list = {}
    try:
        blog_posts = BlogPost.query.filter(BlogPost.hidden!=1).order_by(BlogPost.id.desc()).all()
    except exc.SQLAlchemyError:
        current_app.logger.exception("Unable to get blog posts")
    except exc.NoResultFound:
        no_posts = True
        blog_posts = None
    for post in blog_posts:
        soup = BeautifulSoup(post.body, features="html.parser")
        preview_list[post.id] = soup.get_text()[:400]
    return render_template("main/all_posts.html", blog_posts=blog_posts, no_posts=no_posts, preview_list=preview_list)

app/templates/main/about_me.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
{% if about_me is none %}
    <h3 class="text-center">This page is still under construction. Please check back later.</h3>
{% else %}
    {% if about_me.title is not none %}
        <h3 id="about_me_title">{{ about_me.title }}</h3>
    {% endif %}
    <div id="about_me_content">
        {{ about_me.body|safe }}
    </div>
    <br><br>
    <div id="social_media_separator"></div>
    <br><br>
    <div class="row no-gutters" id="social_icons">
        <div class="col-sm padding-0" id="github_link">
            <a href="{{ about_me.git_url }}" target="_blank"><img src="{{ url_for('static', filename='images/GitHub-Mark.png') }}" class="social_icon" alt="GitHub Icon Image"></a>
        </div>
        <div class="col-sm padding-0" id="linkedin_link">
            <a href="{{ about_me.linkedin_url }}" target="_blank"><img src="{{ url_for('static', filename='images/LinkedIn_Icon.png') }}" class="social_icon" alt="LinkedIn Icon Image"></a>
        </div>
        <div class="col-sm padding-0" id="twitter_link">
            <a href="{{ about_me.twitter_url }}" target="_blank"><img src="{{ url_for('static', filename='images/Twitter-Icon.png') }}" class="social_icon" alt="Twitter Icon Image"></a>
        </div>
        <div class="col-sm padding-0" id="email_link">
            <a href="mailto:{{ about_me.email_addr }}" target="_blank"><img src="{{ url_for('static', filename='images/Email_Icon.jpg') }}" class="social_icon" alt="Email Icon Image"></a>
        </div>
    </div>
{% endif %}
{% endblock %}

app/templates/main/all_posts.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
{% if blog_posts is not none %}
    {% for post in blog_posts %}
        <div class="post_preview">
            <h3><a href="{{ url_for('main.post', post_id=post.id) }}">{{ post.title }}</a></h3>
            <p>{{ preview_list[post.id] }}...</p>
            {% if post.tags is not none %}
            <span>{{ post.tags }}</span>
            {% endif %}
        </div>
    <br>
  {% endfor %}
{% else %}
  <h3 class="text-center">No Posts Available</h3>
{% endif %}
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
{% if blog_posts is not none %}
{% for post in blog_posts %}
<div class="post_preview">
<h3><a href="{{ url_for('main.post', post_id=post.id) }}">{{ post.title }}</a></h3>
<p>{{ preview_list[post.id] }}...</p>
{% if post.tags is not none %}
<span>{{ post.tags }}</span>
{% endif %}
</div>
<br>
{% endfor %}
{% else %}
<h3 class="text-center">No Posts Available</h3>
{% endif %}
{% endblock %}

app/templates/main/post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
{% if error is not none %}
    <h2 id="error_header">{{ error }}</h2>
{% else %}
    <h2 id="post_title">{{ blog_post.title }}</h2>
    <br><br>
    <div id="post_body">
        {{ blog_post.body|safe }}
    </div>
{% endif %}
{% endblock %}
</html>